<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>disable</Nullable>
    <DevServerPath>D:\OtherGames\SPT4.1.X\SPT-4.1.X</DevServerPath>
    <DevGamePluginsMiyakoCarryServicePath>$(DevServerPath)\SPT_Runtime\user\mods\MiyakoCarryServiceServer</DevGamePluginsMiyakoCarryServicePath>
    <BuildMiyakoCarryServicePath>$(ProjectDir)../Build/Plugin/SPT_Runtime/user/mods/MiyakoCarryServiceServer</BuildMiyakoCarryServicePath>  
    <OutputType>Library</OutputType>
    <AssemblyName>Himesamanoyume.MiyakoCarryServiceServer</AssemblyName>
    <AssemblyCompany>Himesamanoyume</AssemblyCompany>
    <AssemblyProduct>MiyakoCarryService</AssemblyProduct>  
    <AssemblyCopyright>Copyright © 姫様の夢 2025 - 2026</AssemblyCopyright> 
    <AssemblyTitle>MiyakoCarryServiceServer</AssemblyTitle>  
    <Version>1.1.1.0</Version>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <Trademark>https://sp-mod.com/mod/2709/miyako-carry-service</Trademark>
    <RootNamespace>MiyakoCarryService.Server</RootNamespace>
    <NoWarn>CS0618;CS8632;CS9107</NoWarn>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>
  <ItemGroup>
      <Content Include="Assets\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.1.0" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Server.Web" Version="4.1.0" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <ServerAssets Include="$(TargetDir)Assets\**\*.*" />
    </ItemGroup>
    <MakeDir Directories="$(DevGamePluginsMiyakoCarryServicePath)" Condition="'$([MSBuild]::IsOSPlatform(Windows))' and Exists('$(DevServerPath)')" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DevGamePluginsMiyakoCarryServicePath)" Condition="'$([MSBuild]::IsOSPlatform(Windows))' and Exists('$(DevServerPath)')" />
    <MakeDir Directories="$(BuildMiyakoCarryServicePath)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BuildMiyakoCarryServicePath)" />
    <Copy SourceFiles="@(ServerAssets)" DestinationFiles="@(ServerAssets->'$(BuildMiyakoCarryServicePath)\Assets\%(RecursiveDir)%(Filename)%(Extension)')" />
    <Copy SourceFiles="@(ServerAssets)" DestinationFiles="@(ServerAssets->'$(DevGamePluginsMiyakoCarryServicePath)\Assets\%(RecursiveDir)%(Filename)%(Extension)')" Condition="'$([MSBuild]::IsOSPlatform(Windows))' and Exists('$(DevServerPath)')" />
  </Target>
</Project>
